name: Upload dotnet package to Nuget

on:
  push:
    branches: [ main ]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - run: dotnet build -c Release
      - name: Create the package
        run: dotnet pack -c Release
      - name: Publish the package to nuget
        run: dotnet nuget push **/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}}
